# Generated by Django 5.0.6 on 2024-06-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('adv_id', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
